### ISSUE TITLE
P2D/P3D issue

### ISSUE THREAD

**Issue by jumahe** [gohai/processing-uploadtopi#8]
Hello.
It looks like using P2D or P3D in the size definition of the sketch (or in fullScreen) causes an error:
```
libEGL warning: DRI2: failed to authenticate
java.lang.RuntimeException: java.lang.ClassNotFoundException: Failed to find NEWT Display Class <.bcm.vc.iv.DisplayDriver>
...
```
However, only writing size(800,600) or fullScreen() instead of size(800,600,P2D) or fullScreen(P2D) let the sketch execute correctly on the RPi.
It looks like some OpenGL lib/class related issue: any idea on how to avoid this if we want to use P2D or P3D capabilities on the Pi?

Good to know: RPi on Raspbian Pixel (Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux).

Thxs a lot.

**Comment by gohai** [comment]
@jumahe I am closing this issue, since this is not related to the UploadToPi tool, but to Processing proper. Feel free to re-open this over at https://github.com/processing/processing.

The error message indicates that parts of the 3D renderer are having troubles loading a class. I have seen similar issues most commonly with folks trying to use parts of Processing from within Eclipse or similar (customized) setups, where the class-paths aren't correctly set. Is this the case here perhasp?
